### ISSUE TITLE
Right stick not turning rover zero

### ISSUE THREAD

**Issue by bgilreath** [RoverRobotics/rr_openrover_stack#58]
In rr_control_input_manager/scripts/xbox_mapper.py

Line 298:
R_STICK_H_AXES]  # right joystick

Needs to change to:
L_STICK_H_AXES]  # left joystick, horizontal axis

to make Rover Zero turn right/left.

**Comment by rookrobotic** [comment]
@bgilreath Have you disabled xpad and enable xboxdrv? There are instructions on how to do this here:
https://roverrobotics.com/pages/rover-zero-tutorial-2

xpad is the default xbox driver for linux but we don't use it because if the batteries on the controller run out xpad will keep sending the last command that was received causing your robot to run away. xboxdrv does not have this problem.
